<?php
function getProfileLink(): string
{
    if (isset($_SESSION["user"])) {
        $url = "/views/profile.phtml";
        $linkText = "Profil";
    }
    else if (isset($_COOKIE["exam_engine_login"])) {
        $url = "/views/login.phtml";
        $linkText = "Prijava";
    }
    else {
        $url = "/views/register.phtml";
        $linkText = "Registracija";
    }

    return "<a href='$url'>$linkText</a>";
}
?>
<h1>Exam Engine</h1>
<hr>

<nav>
    <a href="/views/home.phtml">Početna</a>
    <?php echo getProfileLink(); ?>
    <a href="/">O nama</a>
</nav>

<hr>
