<?php
session_start();
?>
<!DOCTYPE html>
<html lang="hr">
<head>
    <?php require_once "head.phtml"; setPageTitle("O nama"); ?>
</head>
<body>
    <header>
        <?php require_once "header.phtml"; ?>
    </header>

    <main>
        <h2>O Exam Engine</h2>
        
        <p>Dobro došli na opisnu stranicu usluge Exam Engine!</p>
    </main>

    <footer>
        <?php require_once "footer.phtml"; ?>
    </footer>
</body>
</html>
