<?php
session_start();

// User has to be logged in to use this page. If not, redirect:
if (! isset($_SESSION["userID"]))
    Util::redirect("/views/login.phtml");
?>
<!DOCTYPE html>
<html lang="hr">
<head>
    <?php require_once "head.phtml"; setPageTitle("Početna"); ?>

    <script>
        function showOverlay(overlayID)
        {
            const overlay = document.getElementById(overlayID).style.display = "flex";
        }
        function hideOverlay(overlayID)
        {
            const overlay = document.getElementById(overlayID).style.display = "none";
        }
    </script>
</head>
<body>
    <header>
        <?php require_once "header.phtml"; ?>
    </header>

    <main>
        <h2>Moji dokumenti</h2>
        
        <?php require_once "list_documents.php" ?>

        
        <div class="overlay" id="create-document-overlay">
            <form action="/api/create_document.php" method="post" class="form">
            <h3>Napravi novi dokument</h3>
            <label required for="name">Naziv</label>
            <input autofocus required type="text" name="name" value="Novi dokument">

            <label required for="type">Vrsta</label>
            <select required name="type">
                <option value="exam">Ispit</option>
                <option value="form">Obrazac</option>
            </select>

            <label for="deadline">Rok za predaju</label>
            <div>
            <input type="date" name="deadlineDate">
            <input type="time" name="deadlineTime" value="00:00" min="00:00">
            </div>

            <label for="password">Lozinka</label>
            <input type="text" name="password">

            <input type="submit" value="Dodaj">

            <button type="button" class="close-overlay" onclick="hideOverlay('create-document-overlay');">&times;</button>

            <?php echo Util::getFormMsg(); ?>
        </form>
        </div>

        <button onclick="this.blur(); showOverlay('create-document-overlay');">Napravi novi dokument</button>

        <hr>

        <h2>Povijest rješavanja</h2>

        <p>Popis tuđih ispita i obrazaca koje ste predali.</p>

        <?php require_once "list_submissions.php" ?>
    </main>

    <footer>
        <?php require_once "footer.phtml"; ?>
    </footer>
</body>
</html>
