<?php
session_start();

// User has to be logged out to use this page. If not, redirect:
if (isset($_SESSION["userID"]))
    Util::redirect("/views/home.phtml");
?>
<!DOCTYPE html>
<html lang="hr">
<head>
    <?php require_once "head.phtml"; setPageTitle("Prijava"); ?>
</head>
<body>
    <header>
        <?php require_once "header.phtml"; ?>
    </header>

    <main class="form-center">
        <form action="/api/login_process.php" method="post" class="form">
            <h2>Prijava</h2>
            <label required for="emailOrPassword">E-mail ili korisničko ime</label>
            <input required type="text" name="emailOrPassword">
            <br>
            <label required for="password">Lozinka</label>
            <input required type="password" name="password">
            <br>
            <input type="submit" value="Prijavi me">
            <?php echo Util::getFormMsg(); ?>
            <small>
                Nemate račun? <a href="/views/register.phtml">Registrirajte se</a>
            </small>
        </form>

    </main>

    <footer>
        <?php require_once "footer.phtml"; ?>
    </footer>
</body>
</html>
