<?php
session_start();

// User has to be logged in to use this page. If not, redirect:
if (! isset($_SESSION["userID"]))
    Util::redirect("/");
?>
<!DOCTYPE html>
<html lang="hr">
<head>
    <?php require_once "head.phtml"; setPageTitle("Profil"); ?>
</head>
<body>
    <header>
        <?php require_once "header.phtml"; ?>
    </header>

    <main>
        <h2>Profil</h2>
        
<?php
    $user = User::load($_SESSION["userID"]);

    echo "<p>Dobro došli, {$user["firstName"]} {$user["lastName"]}!</p>";
    
    echo "<ul>";
    foreach ($user as $key => $value)
        echo "<li>$key => $value</li>";
        
    echo "</ul>";
?>

    <a href="/api/logout.php">Odjavi me</a>
    </main>

    <footer>
        <?php require_once "footer.phtml"; ?>
    </footer>
</body>
</html>
