<?php
session_start();

// User has to be logged out to use this page. If not, redirect:
if (isset($_SESSION["userID"]))
    Util::redirect("/");
?>
<!DOCTYPE html>
<html lang="hr">
<head>
    <?php require_once "head.phtml"; setPageTitle("Registracija"); ?>
</head>
<body>
    <header>
        <?php require_once "header.phtml"; ?>
    </header>

    <main class="form-center">
        <form method="post" action="/api/register_process.php" class="form">
            <h2>Registracija</h2>
            <label required for="username">Korisničko ime</label>
            <input required type="text" name="username">
            <br>
            <label required for="email">E-mail</label>
            <input required type="email" name="email">
            <br>
            <label required for="password">Lozinka</label>
            <input required type="password" name="password">
            <br>
            <label required for="passwordConfirm">Potvrdi lozinku</label>
            <input required type="password" name="passwordConfirm">
            <br>
            <label required for="firstName">Ime</label>
            <input required type="text" name="firstName">
            <br>
            <label required for="lastName">Prezime</label>
            <input required type="text" name="lastName">
            <br>
            <input type="submit" value="Registriraj me">
            <?php echo Util::getFormMsg(); ?>
            <small>Imate račun? <a href="/views/login.phtml">Prijavite se</a></small>
        </form>

    </main>

    <footer>
        <?php require_once "footer.phtml"; ?>
    </footer>
</body>
</html>
